-- Your SQL goes here

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user VARCHAR(255) NOT NULL,
  community VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user) REFERENCES users(username),
  FOREIGN KEY (community) REFERENCES communities(name)
)
